import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'vi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'explore.title': 'SoloTravel',
    'explore.searchPlaceholder': 'Where do you want to go?',
    'explore.quickPlanner': 'Quick Trip Planner',
    'explore.quickPlannerDesc': 'Find your perfect solo match based on your preferences.',
    'explore.startPlanning': 'Start Planning',
    'explore.dailyInspiration': 'Daily Inspiration',
    'explore.viewAll': 'View all',
    'explore.bestTrips': 'Best Solo Trips This Month',
    'explore.days': '5-7 Days',
    'explore.budget': 'Mid-range',
    'explore.month': 'October',
    'explore.datePlaceholder': 'Select dates',
    'splash.title1': 'Plan smarter.',
    'splash.title2': 'Travel solo',
    'splash.title3': 'with confidence.',
    'splash.subtitle': 'The ultimate companion for independent adventurers. Discover, plan, and connect with ease.',
    'splash.startPlanning': 'Start planning',
    'splash.exploreFirst': 'Explore first',
    'splash.routes': 'Routes',
    'splash.countries': 'Countries',
    'splash.rating': 'Rating',
    'splash.destinations': 'Destinations',
    'splash.safetyGuide': 'Safety Guide',
    'splash.login': 'Log in',
    'onboarding.title': 'Travel Profile',
    'onboarding.step': 'Step 2 of 5',
    'onboarding.defining': 'Defining your solo adventure style',
    'onboarding.question': 'What\'s your travel style?',
    'onboarding.desc': 'Select the vibe that best matches how you like to see the world alone.',
    'onboarding.slowTitle': 'Slow & Immersive',
    'onboarding.slowDesc': 'Deep dives into local culture and hidden gems',
    'onboarding.fastTitle': 'Fast-Paced Explorer',
    'onboarding.fastDesc': 'See as much as possible in the shortest time',
    'onboarding.luxuryTitle': 'Luxury Seeker',
    'onboarding.luxuryDesc': 'Premium stays, comfort, and curated experiences',
    'onboarding.budgetTitle': 'Budget Backpacker',
    'onboarding.budgetDesc': 'Authentic low-cost adventures and social hostels',
    'onboarding.continue': 'Continue',
    'itinerary.title': 'Smart Itinerary',
    'itinerary.transport': 'Transport',
    'itinerary.activities': 'Activities',
    'itinerary.duration': 'Duration',
    'itinerary.flight': 'Flight',
    'itinerary.train': 'Train',
    'itinerary.bus': 'Bus',
    'itinerary.car': 'Car',
    'itinerary.sightseeing': 'Sightseeing',
    'itinerary.food': 'Food',
    'itinerary.nature': 'Nature',
    'itinerary.adventure': 'Adventure',
    'itinerary.days': 'Days',
    'itinerary.day': 'Day',
    'itinerary.relaxPlan': 'Relax Plan',
    'itinerary.moreFood': 'More Food',
    'itinerary.saferVersion': 'Safer Version',
    'itinerary.addItem': 'Add Item',
    'itinerary.addTransport': 'Add Transport',
    'itinerary.addActivity': 'Add Activity',
    'itinerary.addFood': 'Add Food',
    'itinerary.addAccommodation': 'Add Stay',
    'itinerary.itemTitle': 'Title',
    'itinerary.itemTime': 'Time',
    'itinerary.itemLocation': 'Location',
    'itinerary.itemCost': 'Price/Cost',
    'itinerary.cancel': 'Cancel',
    'itinerary.save': 'Save',
    'itinerary.type': 'Type',
    'itinerary.editItem': 'Edit Item',
    'itinerary.deleteItem': 'Delete Item',
    'itinerary.confirmDelete': 'Are you sure you want to delete this item?',
    'itinerary.tripSummary': 'Trip Summary',
    'itinerary.customize': 'Customize',
    'itinerary.places': 'Places',
    'dest.whyFits': 'Why this fits you',
    'dest.matchesAesthetic': 'Matches your aesthetic',
    'dest.matchesAestheticDesc': 'Based on your saved inspiration, you love vertical coastal architecture and vibrant Mediterranean hues.',
    'dest.culinary': 'Culinary alignment',
    'dest.culinaryDesc': 'Positano\'s focus on fresh seafood and lemon-infused cuisine perfectly matches your diet preferences.',
    'dest.neighborhoods': 'Recommended Neighborhoods',
    'dest.seeAll': 'See All',
    'dest.experiences': 'Must-try experiences',
    'dest.foodHighlights': 'Food highlights',
    'dest.safetyRating': 'Solo safety rating',
    'dest.safetyDesc': 'Extremely safe for solo travelers. Well-lit main streets, friendly locals, and a high volume of international visitors year-round.',
    'dest.buildItinerary': 'Build itinerary',
    'food.title': 'Food Discovery',
    'food.search': 'Search food spots, cuisines...',
    'food.soloFriendly': 'Solo friendly',
    'food.localBreakfast': 'Local breakfast',
    'food.addToItinerary': 'Add to itinerary',
    'food.mapView': 'Map View',
    'food.reviews': 'reviews',
    'food.away': 'away',
    'food.openLate': 'OPEN LATE',
    'food.localFavorite': 'LOCAL FAVORITE',
    'journal.newEntry': 'New Entry',
    'journal.vibe': 'HOW\'S THE VIBE?',
    'journal.amazing': 'Amazing',
    'journal.good': 'Good',
    'journal.neutral': 'Neutral',
    'journal.tiring': 'Tiring',
    'journal.capture': 'CAPTURE A MEMORY',
    'journal.addPhoto': 'Add Photo',
    'journal.thoughts': 'THOUGHTS',
    'journal.thoughtsPlaceholder': 'What made today special?',
    'journal.timeline': 'TRIP TIMELINE',
    'recap.title': 'European Adventure Recap',
    'recap.completed': 'COMPLETED',
    'recap.distance': 'DISTANCE',
    'recap.visited': 'VISITED',
    'recap.budget': 'BUDGET',
    'recap.memories': 'MEMORIES',
    'recap.countries': 'Countries',
    'recap.photos': 'Photos',
    'recap.route': 'Route Traveled',
    'recap.fullMap': 'Full Map',
    'recap.bestMemories': 'Best Memories',
    'recap.viewAll': 'View All',
    'recap.planNext': 'Plan Next Trip',
    'recap.shareVideo': 'Share Recap Video',
    'nav.explore': 'Explore',
    'nav.itinerary': 'Itinerary',
    'nav.saved': 'Saved',
    'nav.profile': 'Profile',
    'nav.trips': 'Trips',
    'nav.journal': 'Journal',
    'nav.map': 'Map',
    'nav.memories': 'Memories',
  },
  vi: {
    'explore.title': 'Du Lịch Bụi',
    'explore.searchPlaceholder': 'Bạn muốn đi đâu?',
    'explore.quickPlanner': 'Lên Kế Hoạch Nhanh',
    'explore.quickPlannerDesc': 'Tìm chuyến đi hoàn hảo dựa trên sở thích của bạn.',
    'explore.startPlanning': 'Bắt Đầu Lên Kế Hoạch',
    'explore.dailyInspiration': 'Cảm Hứng Mỗi Ngày',
    'explore.viewAll': 'Xem tất cả',
    'explore.bestTrips': 'Chuyến Đi Tốt Nhất Tháng Này',
    'explore.days': '5-7 Ngày',
    'explore.budget': 'Tầm trung',
    'explore.month': 'Tháng 10',
    'explore.datePlaceholder': 'Chọn ngày',
    'splash.title1': 'Lên kế hoạch thông minh.',
    'splash.title2': 'Du lịch một mình',
    'splash.title3': 'với sự tự tin.',
    'splash.subtitle': 'Người bạn đồng hành tuyệt vời cho những nhà thám hiểm độc lập. Khám phá, lên kế hoạch và kết nối dễ dàng.',
    'splash.startPlanning': 'Bắt đầu lên kế hoạch',
    'splash.exploreFirst': 'Khám phá trước',
    'splash.routes': 'Tuyến đường',
    'splash.countries': 'Quốc gia',
    'splash.rating': 'Đánh giá',
    'splash.destinations': 'Điểm đến',
    'splash.safetyGuide': 'Hướng dẫn an toàn',
    'splash.login': 'Đăng nhập',
    'onboarding.title': 'Hồ sơ du lịch',
    'onboarding.step': 'Bước 2 trên 5',
    'onboarding.defining': 'Xác định phong cách phiêu lưu độc lập của bạn',
    'onboarding.question': 'Phong cách du lịch của bạn là gì?',
    'onboarding.desc': 'Chọn phong cách phù hợp nhất với cách bạn muốn khám phá thế giới một mình.',
    'onboarding.slowTitle': 'Chậm & Sâu sắc',
    'onboarding.slowDesc': 'Khám phá sâu văn hóa địa phương và những viên ngọc ẩn',
    'onboarding.fastTitle': 'Khám phá nhanh',
    'onboarding.fastDesc': 'Xem càng nhiều càng tốt trong thời gian ngắn nhất',
    'onboarding.luxuryTitle': 'Tìm kiếm sự sang trọng',
    'onboarding.luxuryDesc': 'Nơi ở cao cấp, thoải mái và trải nghiệm được tuyển chọn',
    'onboarding.budgetTitle': 'Tây ba lô tiết kiệm',
    'onboarding.budgetDesc': 'Những cuộc phiêu lưu giá rẻ đích thực và nhà nghỉ xã hội',
    'onboarding.continue': 'Tiếp tục',
    'itinerary.title': 'Lịch trình thông minh',
    'itinerary.transport': 'Phương tiện',
    'itinerary.activities': 'Hoạt động',
    'itinerary.duration': 'Thời gian',
    'itinerary.flight': 'Máy bay',
    'itinerary.train': 'Tàu hỏa',
    'itinerary.bus': 'Xe buýt',
    'itinerary.car': 'Ô tô',
    'itinerary.sightseeing': 'Ngắm cảnh',
    'itinerary.food': 'Ẩm thực',
    'itinerary.nature': 'Thiên nhiên',
    'itinerary.adventure': 'Phiêu lưu',
    'itinerary.days': 'Ngày',
    'itinerary.day': 'Ngày',
    'itinerary.relaxPlan': 'Kế hoạch thư giãn',
    'itinerary.moreFood': 'Thêm ẩm thực',
    'itinerary.saferVersion': 'Phiên bản an toàn hơn',
    'itinerary.addItem': 'Thêm lịch trình',
    'itinerary.addTransport': 'Thêm phương tiện',
    'itinerary.addActivity': 'Thêm hoạt động',
    'itinerary.addFood': 'Thêm ăn uống',
    'itinerary.addAccommodation': 'Thêm lưu trú',
    'itinerary.itemTitle': 'Tiêu đề',
    'itinerary.itemTime': 'Thời gian',
    'itinerary.itemLocation': 'Địa điểm',
    'itinerary.itemCost': 'Giá tiền',
    'itinerary.cancel': 'Hủy',
    'itinerary.save': 'Lưu',
    'itinerary.type': 'Loại',
    'itinerary.editItem': 'Sửa lịch trình',
    'itinerary.deleteItem': 'Xóa lịch trình',
    'itinerary.confirmDelete': 'Bạn có chắc chắn muốn xóa lịch trình này không?',
    'itinerary.tripSummary': 'Tổng quan chuyến đi',
    'itinerary.customize': 'Tùy chỉnh',
    'itinerary.places': 'Địa điểm',
    'dest.whyFits': 'Tại sao nơi này phù hợp với bạn',
    'dest.matchesAesthetic': 'Phù hợp với thẩm mỹ của bạn',
    'dest.matchesAestheticDesc': 'Dựa trên nguồn cảm hứng đã lưu, bạn yêu thích kiến trúc ven biển thẳng đứng và màu sắc rực rỡ của Địa Trung Hải.',
    'dest.culinary': 'Phù hợp ẩm thực',
    'dest.culinaryDesc': 'Sự tập trung của Positano vào hải sản tươi sống và ẩm thực hương chanh hoàn toàn phù hợp với sở thích ăn kiêng của bạn.',
    'dest.neighborhoods': 'Khu vực được đề xuất',
    'dest.seeAll': 'Xem tất cả',
    'dest.experiences': 'Trải nghiệm phải thử',
    'dest.foodHighlights': 'Điểm nhấn ẩm thực',
    'dest.safetyRating': 'Đánh giá an toàn cho người đi một mình',
    'dest.safetyDesc': 'Cực kỳ an toàn cho du khách đi một mình. Đường phố chính đủ ánh sáng, người dân địa phương thân thiện và lượng lớn du khách quốc tế quanh năm.',
    'dest.buildItinerary': 'Tạo lịch trình',
    'food.title': 'Khám phá ẩm thực',
    'food.search': 'Tìm kiếm địa điểm ăn uống, ẩm thực...',
    'food.soloFriendly': 'Thân thiện đi một mình',
    'food.localBreakfast': 'Bữa sáng địa phương',
    'food.addToItinerary': 'Thêm vào lịch trình',
    'food.mapView': 'Xem bản đồ',
    'food.reviews': 'đánh giá',
    'food.away': 'cách đây',
    'food.openLate': 'MỞ CỬA MUỘN',
    'food.localFavorite': 'ĐỊA PHƯƠNG YÊU THÍCH',
    'journal.newEntry': 'Bài viết mới',
    'journal.vibe': 'CẢM GIÁC THẾ NÀO?',
    'journal.amazing': 'Tuyệt vời',
    'journal.good': 'Tốt',
    'journal.neutral': 'Bình thường',
    'journal.tiring': 'Mệt mỏi',
    'journal.capture': 'LƯU GIỮ KỶ NIỆM',
    'journal.addPhoto': 'Thêm ảnh',
    'journal.thoughts': 'SUY NGHĨ',
    'journal.thoughtsPlaceholder': 'Điều gì làm cho ngày hôm nay trở nên đặc biệt?',
    'journal.timeline': 'DÒNG THỜI GIAN CHUYẾN ĐI',
    'recap.title': 'Tóm tắt chuyến phiêu lưu Châu Âu',
    'recap.completed': 'ĐÃ HOÀN THÀNH',
    'recap.distance': 'KHOẢNG CÁCH',
    'recap.visited': 'ĐÃ ĐẾN',
    'recap.budget': 'NGÂN SÁCH',
    'recap.memories': 'KỶ NIỆM',
    'recap.countries': 'Quốc gia',
    'recap.photos': 'Ảnh',
    'recap.route': 'Tuyến đường đã đi',
    'recap.fullMap': 'Bản đồ đầy đủ',
    'recap.bestMemories': 'Kỷ niệm đẹp nhất',
    'recap.viewAll': 'Xem tất cả',
    'recap.planNext': 'Lên kế hoạch chuyến đi tiếp',
    'recap.shareVideo': 'Chia sẻ video tóm tắt',
    'nav.explore': 'Khám phá',
    'nav.itinerary': 'Lịch trình',
    'nav.saved': 'Đã lưu',
    'nav.profile': 'Hồ sơ',
    'nav.trips': 'Chuyến đi',
    'nav.journal': 'Nhật ký',
    'nav.map': 'Bản đồ',
    'nav.memories': 'Kỷ niệm',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
